In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt #visualization
from sklearn.model_selection import train_test_split #for spliting the dataset
from sklearn.linear_model  import LinearRegression 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [63]:
df = pd.read_csv('F:\Machine Learning\Class 06\Agora.csv')
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [64]:
df.T

0          1          2          3          4   \
Marketing Spend  114523.61   162597.7  153441.51  144372.41  142107.34   
Administration    136897.8  151377.59  101145.55  118671.85   91391.77   
Transport         471784.1  443898.53  407934.54  383199.62  366168.42   
Area                 Dhaka        Ctg    Rangpur      Dhaka    Rangpur   
Profit           192261.83  191792.06  191050.39  182901.99  166187.94   

                        5          6          7          8          9   ...  \
Marketing Spend   131876.9  134615.46  130298.13  120542.52  123334.88  ...   
Administration    99814.71  147198.87  145530.06  148718.95  108679.17  ...   
Transport        362861.36  127716.82  323876.68  311613.29  304981.62  ...   
Area                 Dhaka        Ctg    Rangpur      Dhaka        Ctg  ...   
Profit           156991.12  156122.51   155752.6  152211.77  149759.96  ...   

                        40         41         42        43         44  \
Marketing Spend   28754.33   27892.92   23640.93  15505.73   22177.74   
Administration   118546.05   84710.77   96189.63  127382.3  154806.14   
Transport        172795.67  164470.71  148001.11  35534.17   28334.72   
Area                   Ctg    Rangpur        Ctg     Dhaka        Ctg   
Profit            78239.91   77798.83   71498.49  69758.98   65200.33   

                        45         46         47        48        49  
Marketing Spend    1000.23    1315.46        0.0    542.05       0.0  
Administration   124153.04  115816.21  135426.92  51743.15  116983.8  
Transport          1903.93  297114.46        0.0       0.0  45173.06  
Area                 Dhaka    Rangpur        Ctg     Dhaka       Ctg  
Profit            64926.08   49490.75   42559.73  35673.41   14681.4  

[5 rows x 50 columns]

In [65]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          1
Area               0
Profit             0
dtype: int64

In [66]:
mean = df.Transport.mean()
mean

215331.73244897963

In [67]:
df.Transport = df.Transport.fillna(mean)

In [68]:
df.isnull().sum()

Marketing Spend    0
Administration     0
Transport          0
Area               0
Profit             0
dtype: int64

**Lebel Incoder**

In [69]:
label = LabelEncoder()

In [70]:
df.Area = label.fit_transform(df['Area'])

In [71]:
df.head()

Marketing Spend  Administration  Transport  Area     Profit
0        114523.61       136897.80  471784.10     1  192261.83
1        162597.70       151377.59  443898.53     0  191792.06
2        153441.51       101145.55  407934.54     2  191050.39
3        144372.41       118671.85  383199.62     1  182901.99
4        142107.34        91391.77  366168.42     2  166187.94

In [72]:
x = df.drop('Profit',axis=1)
x.head()

Marketing Spend  Administration  Transport  Area
0        114523.61       136897.80  471784.10     1
1        162597.70       151377.59  443898.53     0
2        153441.51       101145.55  407934.54     2
3        144372.41       118671.85  383199.62     1
4        142107.34        91391.77  366168.42     2

In [73]:
y = df.drop(x,axis=1)
y.head()

Profit
0  192261.83
1  191792.06
2  191050.39
3  182901.99
4  166187.94

**Standardization**

In [74]:
standardScaler = StandardScaler()

In [75]:
new_x = standardScaler.fit_transform(x)
df = pd.DataFrame(new_x, columns = x.columns)

In [76]:
df.head()

Marketing Spend  Administration  Transport      Area
0         0.897913        0.560753   2.187271  0.024626
1         1.955860        1.082807   1.949436 -1.206662
2         1.754364       -0.728257   1.642701  1.255914
3         1.554784       -0.096365   1.431738  0.024626
4         1.504937       -1.079919   1.286479  1.255914

**dataset spliting**

In [77]:
xtrain, xtest, ytrain, ytest = train_test_split(new_x, y, test_size = .30, random_state = 12)

In [78]:
xtrain

array([[ 1.01718075,  1.26919939,  0.35123249,  1.25591385],
       [ 0.0353702 ,  0.82171792, -0.69324763,  1.25591385],
       [ 1.09181921, -0.45664025,  0.76461985, -1.20666232],
       [-0.40112892, -0.65932403, -0.00594402,  1.25591385],
       [-1.62236202,  0.50772188, -1.83655463, -1.20666232],
       [ 0.05572609, -0.26958765,  0.71074116, -1.20666232],
       [ 0.0944412 ,  0.00911842,  0.41804099, -1.20666232],
       [ 0.0731146 , -0.79546917, -0.63759842,  0.02462576],
       [-1.10210556, -0.90693753, -0.57425984, -1.20666232],
       [-0.22694868,  0.28392381, -1.44349561, -1.20666232],
       [-0.60974994, -1.30865753, -0.08370395,  0.02462576],
       [-0.13620072, -0.56221127,  0.76280412,  1.25591385],
       [ 1.95586034,  1.08280658,  1.94943591, -1.20666232],
       [-0.25807437, -0.20562866, -1.0593004 ,  1.25591385],
       [ 1.5049372 , -1.07991935,  1.2864793 ,  1.25591385],
       [-1.13430539,  1.20641936, -1.59488908, -1.20666232],
       [-0.77382036, -1.

In [79]:
ytrain.head()

Profit
14  132602.65
26  105733.54
9   149759.96
33   96778.92
47   42559.73

In [80]:
xtest

array([[-1.68792717e-01,  2.21014050e+00, -8.28873964e-01,
         1.25591385e+00],
       [-1.59341322e+00, -1.99321741e-01,  6.97521194e-01,
         1.25591385e+00],
       [ 1.24505666e+00,  8.71980011e-01,  9.25774961e-01,
         1.25591385e+00],
       [-1.00853372e+00, -1.32079581e+00, -4.33791366e-01,
         1.25591385e+00],
       [-9.91570153e-01,  2.05924691e-01, -1.21153057e-01,
         1.25591385e+00],
       [-1.78608540e-01,  1.14245677e+00, -9.22776222e-01,
         2.46257617e-02],
       [ 1.02723599e-01,  1.16918609e+00,  7.19891193e-01,
         2.46257617e-02],
       [-1.61043334e+00, -2.50940884e+00, -1.83655463e+00,
         2.46257617e-02],
       [ 2.79441650e-01,  1.15983657e+00,  4.96450514e-16,
         2.46257617e-02],
       [ 1.03036886e+00,  9.86952101e-01,  8.21181061e-01,
         2.46257617e-02],
       [ 4.60720127e-01,  8.55666318e-01,  5.73508910e-01,
         2.46257617e-02],
       [-1.17717755e+00, -1.99727037e+00, -2.56436952e-01,
      

In [81]:
ytest.head()

Profit
28  103282.38
46   49490.75
7   155752.60
41   77798.83
36   90708.19

**train the model**

In [82]:
from sklearn.linear_model  import SGDRegressor

In [83]:
sgd = SGDRegressor()

In [84]:
sgd.fit(xtrain, ytrain)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SGDRegressor()

In [85]:
ypred = sgd.predict(xtest)
ypred

array([103696.34539075,  64466.39406775, 164130.18767831,  73710.13464086,
        78826.54703928, 101648.76807207, 124513.19020291,  40816.86535974,
       124685.6823926 , 156597.96793214, 135075.78865097,  68976.10299364,
        87361.57918081, 185411.87673459,  96988.72379186])

**MSE**

In [86]:
mean_squared_error(ytest, ypred)

267164022.29067802

**score**

In [87]:
sgd.score(xtest, ytest)## R-squard value

0.7450953086204477

**r2_score**

In [88]:
r2_score(ytest, ypred) ## R-squard value

0.7450953086204477